fixup

diff --git a/.devcontainer/Makefile.dev b/.devcontainer/Makefile.dev
--- a/.devcontainer/Makefile.dev
+++ b/.devcontainer/Makefile.dev
@@ -11,7 +11,22 @@ else
 	$(MAKE) _setup_vscode
 endif
 
-_prebuild:
+_validations:
+ifeq ($(strip $(editor)), cli)
+ifeq ($(strip $(infra)), pod)
+ifeq ($(strip $(runtime)), docker)
+	echo "Invalid configuration. Docker doens't support local pods"
+	exit 1
+endif
+endif
+endif
+
+Makefile: _makegen
+	# sed -i "s/project-name/$(project_name)/g" .gitignore
+	# sed -i '1,25d' Makefile
+	# sed -i 's/devcontainer: gendevenv/devcontainer:/g' Makefile
+
+_prebuild: _validations
 	-mv project-name $(project_name)
 	sed -i "s/project-name/$(project_name)/g" $(project_name)/*
 	sed -i "s/project-name/$(project_name)/g" docker-compose.yaml
@@ -107,59 +122,67 @@ envpurge: envdestroy
 ifeq ($(strip $(editor)), cli)
 	$(runtime) image rm localhost/$(project_name):dev
 else
-	$(runtime) container rm vscode-$(container_name)
+	# $(runtime) container rm vscode-$(container_name)
 endif
 
-gendevenv: _prebuild
-	rm -f Makefile.dev
-	echo -e "all:" >> Makefile.dev
-	echo -e "\nenvcreate:" >> Makefile.dev
+_makegen: _prebuild
+	rm -f Makefile
+	echo -e "all:" >> Makefile
+	echo -e "\nenvcreate:" >> Makefile
 ifeq ($(strip $(editor)), cli)
 ifeq ($(strip $(infra)), pod)
-	echo -e "\t$(runtime) build -f $(project_name)/Dockerfile -t localhost/$(project_name):dev ." >> Makefile.dev
+	echo -e "\tpodman kube play --replace pod.yaml" >> Makefile
 else
-	echo -e "\t$(runtime) compose build" >> Makefile.dev
+	echo -e "\t$(runtime) compose build" >> Makefile
 endif
 else
-	echo -e "\tdevcontainer build .." >> Makefile.dev
+	echo -e "\tdevcontainer build .." >> Makefile
 endif
-	echo -e "\nenvstart:" >> Makefile.dev
+	echo -e "\nenvstart:" >> Makefile
 ifeq ($(strip $(editor)), cli)
 ifeq ($(strip $(infra)), pod)
-	echo -e "\tpodman pod start $(project_name)" >> Makefile.dev
+	echo -e "\tpodman pod start $(project_name)" >> Makefile
 else
-	echo -e "\t$(runtime) compose up -d" >> Makefile.dev
+	echo -e "\t$(runtime) compose up -d" >> Makefile
 endif
 else
-	echo -e "\tdevcontainer up --docker-path $(runtime) --workspace-folder .." >> Makefile.dev
+	echo -e "\tdevcontainer up --docker-path $(runtime) --workspace-folder .." >> Makefile
 endif
-	echo -e "\nenventer: envstart" >> Makefile.dev
+	echo -e "\nenventer: envstart" >> Makefile
 ifeq ($(strip $(editor)), cli)
 ifeq ($(strip $(infra)), pod)
-	echo -e "\tpodman exec -it -w /workspace $(project_name)-$(container_name) bash" >> Makefile.dev
+	echo -e "\tpodman exec -it -w /workspace $(project_name)-$(container_name) bash" >> Makefile
 else
-	echo -e "\t$(runtime) compose exec -w /workspace development bash" >> Makefile.dev
+	echo -e "\t$(runtime) compose exec -w /workspace development bash" >> Makefile
 endif
 else
-	echo -e "\tdevcontainer open ..  # Ensure that vscode binary is discoverable in $PATH" >> Makefile.dev
+	echo -e "\tdevcontainer open ..  # Ensure that vscode binary is discoverable in $PATH" >> Makefile
 endif
-	echo -e "\nenvstop:" >> Makefile.dev
+	echo -e "\nenvstop:" >> Makefile
 ifeq ($(strip $(editor)), cli)
 ifeq ($(strip $(infra)), pod)
-	echo -e "\tpodman pod stop $(project_name)" >> Makefile.dev
+	echo -e "\tpodman pod stop $(project_name)" >> Makefile
 else
-	echo -e "\t$(runtime) compose stop" >> Makefile.dev
+	echo -e "\t$(runtime) compose stop" >> Makefile
 endif
 else
-	echo -e "\t$(runtime) stop vscode-$(container_name)" >> Makefile.dev
+	echo -e "\t$(runtime) stop vscode-$(container_name)" >> Makefile
 endif
-	echo -e "\nenvdestroy: envstop" >> Makefile.dev
+	echo -e "\nenvdestroy: envstop" >> Makefile
 ifeq ($(strip $(editor)), cli)
 ifeq ($(strip $(infra)), pod)
-	echo -e "\tpodman kube play --down pod.yaml" >> Makefile.dev
+	echo -e "\tpodman kube play --down pod.yaml" >> Makefile
 else
-	echo -e "\t$(runtime) compose down" >> Makefile.dev
+	echo -e "\t$(runtime) compose down" >> Makefile
 endif
 else
-	echo -e "\t$(runtime) container rm vscode-$(container_name)" >> Makefile.dev
+	echo -e "\t$(runtime) container rm vscode-$(container_name)" >> Makefile
 endif
+	echo -e "\nenvpurge: envdestroy" >> Makefile
+ifeq ($(strip $(editor)), cli)
+	echo -e "\t$(runtime) image rm localhost/$(project_name):dev"
+else
+	# $(runtime) container rm vscode-$(container_name)
+endif
+
+gendevenv: Makefile
